jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    # Ajoutez d'autres étapes si nécessaire
    # ...

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run script
      env:
        OPENAI_SECRET: ${{ secrets.OPENAI_SECRET }}
      run: |
        python main.py
