name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Ajoutez d'autres étapes nécessaires ici

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # ou toute autre version nécessaire

    - name: Run script
      run: python main.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

